version: '3.8'

services:
  backend:
    build: .
    environment:
      - MONGO_URI=mongodb+srv://InnoWave:PxEU801XfPNlpmND@cluster0.zekb51t.mongodb.net/InnoWave?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=innowave-jwt-secret-123454321
      - JWT_COOKIE_NAME=innowavejwt
      - PORT=5000
    ports:
      - "5000:5000"